### ISSUE TITLE
Create Pyth backup pusher bot

### ISSUE THREAD

**Issue by rhlsthrm** [ionicprotocol/monorepo#343]
Current bot is here: https://github.com/ionicprotocol/monorepo/blob/b5a081757a787459f49e93867b0df2dddb8d2fa9/packages/bots/pyth-updater

We need to make sure it works to push all our assets with the correct config.

**Comment by jourdanDunkley** [comment]
Started reviewing code

**Comment by TylerEther** [comment]
I was peeking around, and I noticed this. I've been planning on creating a Pyth feed updater bot since Pyth is used in some of our oracles. Would you like me to create and run this for you?

**Comment by rhlsthrm** [comment]
> I was peeking around, and I noticed this. I've been planning on creating a Pyth feed updater bot since Pyth is used in some of our oracles. Would you like me to create and run this for you?

Ah this task is old! We have been using Asana for task management but we are coming back to GitHub so I need to clean things up. 

We are already running our Pyth updater bot now actually! However if you run one we can rely on that instead!

**Comment by rhlsthrm** [comment]
Here's the bot code @TylerEther 

https://github.com/ionicprotocol/monorepo/tree/development/packages/bots/pyth-updater
