### ISSUE TITLE
[USER SUBMITTED BUG] Unable to install the SDK using pnpm 9.5

### ISSUE THREAD

**Issue by aquarat** [ionicprotocol/monorepo#457]
**Describe The Outcome:** 
When trying to install the SDK using pnpm the installation fails with
> pnpm i --save @ionicprotocol/sdk 
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@ionicprotocol/chains@workspace:*" is in the dependencies but no package named "@ionicprotocol/chains" is present in the workspace

**Expected behavior:** 
Installation to occur without failure.

**Steps To Reproduce:** (Steps to reproduce the behavior)
1. Run `pnpm i --save @ionicprotocol/sdk` in an existing project.

**Browser/App/Platform Info**
Mac OS, pnpm 9.5, node 20.15.0

**Comment by rhlsthrm** [comment]
Hi @aquarat, the SDK has not really been deployed as a standalone package. What's your use case? We can help you with this. Sorry for the delayed response.

**Comment by aquarat** [comment]
Hey there
This is no longer an issue for us as we shifted focus and changed our internal searcher approach. I'll close this issue.
