### ISSUE TITLE
Add Velo ION LP to Staking

### ISSUE THREAD

**Issue by Penguionnaire** [ionicprotocol/monorepo#726]
Add Optimism ION pool to Stake page.

Pool: https://velodrome.finance/deposit?token0=0x4200000000000000000000000000000000000006&token1=0x887d1c6A4f3548279c2a8A9D0FA61B5D458d14fC&type=-1&factory=0xF1046053aa5682b4F9a81b5481394DA16BE5FF5a&chain=10

**Comment by vidvidvid** [comment]
rahul:
> 1. router on optimism: https://optimistic.etherscan.io/address/0xa062aE8A9c5e11aaA026fc2670B0D65cCc8B2858#writeContract
> 2. can use same ABI
> 3. staking contract: https://optimistic.etherscan.io/address/0x4d1ffce9ef3adbd119d0bdad5e56706a69f3c0fe
> 4. same
